name: openid_client
description: Library for working with OpenID Connect and implementing clients.
version: 0.4.6
homepage: https://github.com/appsup-dart/openid_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  clock: ^1.1.0
  http: ^0.13.0
  jose: ^0.3.2
  logging: ^1.0.0
  meta: ^1.0.0
  pointycastle: ^3.0.0
  universal_html: ^2.0.8

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.5

executables:
  openid_client: openid_client
